version: '3.8'

services:
  # Единый PostgreSQL контейнер с несколькими базами данных
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: order,user,product
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  # Микросервисы
  user-service:
    build: ./user-microservice
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080

  product-service:
    build: ./product-microservice
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080

  order-service:
    build: ./order-microservice
    ports:
      - "8082:8080"
    environment:
      SERVICE_USER_URL: http://user-service:8080
      SERVICE_PRODUCT_URL: http://product-service:8080/api
      SERVER_PORT: 8080

volumes:
  postgres_data: