server:
  port: 8082

service:
  user:
    url: http://localhost:8080
  product:
    url: http://localhost:8081/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
